<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="pc" name="Default test" tests="2" failures="1" timestamp="26 Sep 2016 14:25:26 GMT" time="0.573" errors="0">
  <testcase name="test" time="0.545" classname="cz.ivantichy.httpapi.handlers.certapi.tun_basic.CreateServerTUNBasicImplTest"/>
  <testcase name="test2" time="0.002" classname="cz.ivantichy.httpapi.handlers.certapi.tun_basic.CreateServerTUNBasicImplTest">
    <failure type="java.io.IOException" message="souce path does not exists">
      <![CDATA[java.io.IOException: souce path does not exists
	at cz.ivantichy.fileutils.FileWork.checkFolder(FileWork.java:66)
	at cz.ivantichy.httpapi.handlers.certapi.tun_basic.CreateServerTUNBasicImpl.create(CreateServerTUNBasicImpl.java:30)
	at cz.ivantichy.httpapi.handlers.certapi.tun_basic.CreateServerTUNBasicImplTest.test2(CreateServerTUNBasicImplTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test -->
